// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HubRequest {
    #[prost(
        oneof = "hub_request::RequestType",
        tags = "1, 2, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21"
    )]
    pub request_type: ::core::option::Option<hub_request::RequestType>,
}
/// Nested message and enum types in `HubRequest`.
pub mod hub_request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum RequestType {
        #[prost(message, tag = "1")]
        ServerHelloReq(super::ServerHelloRequest),
        #[prost(message, tag = "2")]
        ServerHelloRes(super::ServerHelloResponse),
        #[prost(message, tag = "6")]
        KeepAliveReq(super::KeepAliveRequest),
        #[prost(message, tag = "7")]
        KeepAliveRes(super::KeepAliveResponse),
        #[prost(message, tag = "8")]
        NatPokeReq(super::NatPokeRequest),
        #[prost(message, tag = "9")]
        NatPokeRes(super::NatPokeResponse),
        #[prost(message, tag = "10")]
        HealthReq(super::HealthCheckRequest),
        #[prost(message, tag = "11")]
        HealthRes(super::HealthCheckResponse),
        #[prost(message, tag = "12")]
        CheckoutReq(super::CreateCheckoutSessionRequest),
        #[prost(message, tag = "13")]
        CheckoutRes(super::CreateCheckoutSessionResponse),
        #[prost(message, tag = "14")]
        ClientHelloReq(super::ClientHelloRequest),
        #[prost(message, tag = "15")]
        ClientHelloRes(super::ClientHelloResponse),
        #[prost(message, tag = "16")]
        SetHostnameReq(super::SetHostNameRequest),
        #[prost(message, tag = "17")]
        SetHostnameRes(super::SetHostNameResponse),
        #[prost(message, tag = "18")]
        NotifyReq(super::NotifyRequest),
        #[prost(message, tag = "19")]
        DisconnectReq(super::DisconnectRequest),
        #[prost(message, tag = "20")]
        GetHostnameReq(super::GetHostNameRequest),
        #[prost(message, tag = "21")]
        GetHostnameRes(super::GetHostNameResponse),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerHelloRequest {
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ServerHelloResponse {
    #[prost(bool, tag = "1")]
    pub accepted: bool,
    #[prost(string, optional, tag = "2")]
    pub reason: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub hostname: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetHostNameRequest {
    #[prost(string, tag = "1")]
    pub hostname: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub device_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetHostNameResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, optional, tag = "2")]
    pub error: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetHostNameRequest {
    #[prost(string, tag = "1")]
    pub device_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetHostNameResponse {
    #[prost(string, optional, tag = "1")]
    pub hostname: ::core::option::Option<::prost::alloc::string::String>,
}
/// Hub-initiated keep-alive (server only responds)
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KeepAliveRequest {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct KeepAliveResponse {}
/// Hub-initiated NAT traversal
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NatPokeRequest {
    #[prost(string, tag = "1")]
    pub client_socket_addr: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NatPokeResponse {
    #[prost(bool, tag = "1")]
    pub reached: bool,
    #[prost(string, optional, tag = "2")]
    pub private_socket_addr: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthCheckRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HealthCheckResponse {
    #[prost(string, tag = "1")]
    pub status: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub uptime_seconds: i64,
    #[prost(int32, tag = "3")]
    pub active_servers: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateCheckoutSessionRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateCheckoutSessionResponse {
    #[prost(string, tag = "1")]
    pub checkout_url: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
    #[prost(bool, tag = "3")]
    pub new: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClientHelloRequest {
    #[prost(string, tag = "1")]
    pub unique_id: ::prost::alloc::string::String,
    #[prost(string, optional, tag = "2")]
    pub private_socket_addr: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ClientHelloResponse {
    #[prost(bool, tag = "1")]
    pub found: bool,
    #[prost(string, optional, tag = "2")]
    pub socket_addr: ::core::option::Option<::prost::alloc::string::String>,
    #[prost(string, optional, tag = "3")]
    pub secondary_socket_addr: ::core::option::Option<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NotifyRequest {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub event: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DisconnectRequest {
    #[prost(uint64, tag = "1")]
    pub time: u64,
}
