// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Request {
    #[prost(
        oneof = "request::RequestType",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17"
    )]
    pub request_type: ::core::option::Option<request::RequestType>,
}
/// Nested message and enum types in `Request`.
pub mod request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum RequestType {
        #[prost(message, tag = "1")]
        Authenticate(super::AuthenticateRequest),
        #[prost(message, tag = "2")]
        ReadFile(super::ReadFileRequest),
        #[prost(message, tag = "3")]
        WriteFile(super::WriteFileRequest),
        #[prost(message, tag = "4")]
        DeleteFile(super::DeleteFileRequest),
        #[prost(message, tag = "5")]
        RenameFile(super::RenameFileRequest),
        #[prost(message, tag = "6")]
        ListDirectory(super::ListDirectoryRequest),
        #[prost(message, tag = "7")]
        CreateDirectory(super::CreateDirectoryRequest),
        #[prost(message, tag = "8")]
        DeleteDirectory(super::DeleteDirectoryRequest),
        #[prost(message, tag = "9")]
        GetFileInfo(super::GetFileInfoRequest),
        #[prost(message, tag = "10")]
        ListVolumes(super::ListVolumesRequest),
        #[prost(message, tag = "11")]
        GetVolumeInfo(super::GetVolumeInfoRequest),
        #[prost(message, tag = "12")]
        Watch(super::Watch),
        #[prost(message, tag = "13")]
        OpenFile(super::OpenFileRequest),
        #[prost(message, tag = "14")]
        LockFile(super::LockRequest),
        #[prost(message, tag = "15")]
        CreateFile(super::CreateFileRequest),
        #[prost(message, tag = "16")]
        CloseFile(super::CloseFileRequest),
        #[prost(message, tag = "17")]
        OverrideFile(super::OverrideFileRequest),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Response {
    #[prost(oneof = "response::ResponseType", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10")]
    pub response_type: ::core::option::Option<response::ResponseType>,
}
/// Nested message and enum types in `Response`.
pub mod response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ResponseType {
        #[prost(message, tag = "1")]
        AuthenticationSuccess(super::AuthenticationSuccessResponse),
        #[prost(message, tag = "2")]
        FileData(super::FileDataResponse),
        #[prost(message, tag = "3")]
        WriteSuccess(super::WriteSuccessResponse),
        #[prost(message, tag = "4")]
        OperationSuccess(super::OperationSuccessResponse),
        #[prost(message, tag = "5")]
        DirectoryListing(super::DirectoryListingResponse),
        #[prost(message, tag = "6")]
        FileInfo(super::FileInfoResponse),
        #[prost(message, tag = "7")]
        VolumeList(super::VolumeListResponse),
        #[prost(message, tag = "8")]
        VolumeInfo(super::VolumeInfoResponse),
        #[prost(message, tag = "9")]
        Error(super::ErrorResponse),
        #[prost(message, tag = "10")]
        Watch(super::Watch),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthenticateRequest {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CloseFileRequest {
    #[prost(uint64, tag = "1")]
    pub file_handler: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthenticationSuccessResponse {
    #[prost(string, tag = "1")]
    pub host_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(uint32, optional, tag = "3")]
    pub port: ::core::option::Option<u32>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OverrideFileRequest {
    #[prost(uint64, tag = "1")]
    pub file_id: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadFileRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
    #[prost(uint32, tag = "3")]
    pub length: u32,
    #[prost(uint64, tag = "4")]
    pub file_id: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateFileRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub file_id: u64,
    #[prost(uint32, tag = "5")]
    pub flags: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileDataResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpenFileRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub file_id: u64,
    #[prost(uint32, tag = "4")]
    pub flags: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WriteFileRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "5")]
    pub file_id: u64,
    #[prost(uint32, tag = "6")]
    pub flags: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LockRequest {
    #[prost(uint64, tag = "1")]
    pub offset: u64,
    #[prost(uint64, tag = "2")]
    pub length: u64,
    #[prost(uint64, tag = "3")]
    pub file_id: u64,
    #[prost(bool, tag = "4")]
    pub wait: bool,
    #[prost(bool, tag = "5")]
    pub test: bool,
    #[prost(uint32, tag = "6")]
    pub flags: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WriteSuccessResponse {
    #[prost(uint64, tag = "1")]
    pub bytes_written: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteFileRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RenameFileRequest {
    #[prost(string, tag = "1")]
    pub old_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub new_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetFileInfoRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileInfoResponse {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub size: u64,
    #[prost(bool, tag = "4")]
    pub is_directory: bool,
    #[prost(int64, tag = "5")]
    pub created_at: i64,
    #[prost(int64, tag = "6")]
    pub modified_at: i64,
    #[prost(int64, tag = "7")]
    pub accessed_at: i64,
    #[prost(uint32, tag = "8")]
    pub flags: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListDirectoryRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DirectoryListingResponse {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<DirectoryEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DirectoryEntry {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_directory: bool,
    #[prost(uint64, tag = "3")]
    pub size: u64,
    #[prost(int64, tag = "4")]
    pub modified: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateDirectoryRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteDirectoryRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
/// No fields needed
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListVolumesRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VolumeListResponse {
    #[prost(message, repeated, tag = "1")]
    pub volumes: ::prost::alloc::vec::Vec<VolumeInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetVolumeInfoRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VolumeInfoResponse {
    #[prost(message, optional, tag = "1")]
    pub volume: ::core::option::Option<VolumeInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VolumeInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub root_path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub total_size: u64,
    #[prost(uint64, tag = "5")]
    pub available_space: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Watch {
    #[prost(string, tag = "1")]
    pub drive: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "2")]
    pub path: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OperationSuccessResponse {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ErrorResponse {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
    #[prost(enumeration = "ErrorCode", tag = "2")]
    pub code: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ErrorCode {
    InternalError = 0,
    PermissionDenied = 1,
    NotFound = 2,
    AlreadyExists = 3,
    InvalidRequest = 4,
    AuthenticationFailed = 5,
    SessionExpired = 6,
    QuotaExceeded = 7,
    IoError = 8,
}
impl ErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::InternalError => "INTERNAL_ERROR",
            Self::PermissionDenied => "PERMISSION_DENIED",
            Self::NotFound => "NOT_FOUND",
            Self::AlreadyExists => "ALREADY_EXISTS",
            Self::InvalidRequest => "INVALID_REQUEST",
            Self::AuthenticationFailed => "AUTHENTICATION_FAILED",
            Self::SessionExpired => "SESSION_EXPIRED",
            Self::QuotaExceeded => "QUOTA_EXCEEDED",
            Self::IoError => "IO_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INTERNAL_ERROR" => Some(Self::InternalError),
            "PERMISSION_DENIED" => Some(Self::PermissionDenied),
            "NOT_FOUND" => Some(Self::NotFound),
            "ALREADY_EXISTS" => Some(Self::AlreadyExists),
            "INVALID_REQUEST" => Some(Self::InvalidRequest),
            "AUTHENTICATION_FAILED" => Some(Self::AuthenticationFailed),
            "SESSION_EXPIRED" => Some(Self::SessionExpired),
            "QUOTA_EXCEEDED" => Some(Self::QuotaExceeded),
            "IO_ERROR" => Some(Self::IoError),
            _ => None,
        }
    }
}
