// This file is @generated by prost-build.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnixForwardReq {
    #[prost(oneof = "unix_forward_req::UnixForwardReqType", tags = "2")]
    pub unix_forward_req_type: ::core::option::Option<
        unix_forward_req::UnixForwardReqType,
    >,
}
/// Nested message and enum types in `unix_forward_req`.
pub mod unix_forward_req {
    #[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum UnixForwardReqType {
        #[prost(bool, tag = "2")]
        Spindown(bool),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnixForwardRemove {
    #[prost(uint64, tag = "1")]
    pub connection_id: u64,
    #[prost(message, optional, tag = "2")]
    pub remove: ::core::option::Option<RemoveRequest>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UnixForwardRes {
    #[prost(oneof = "unix_forward_res::UnixForwardResType", tags = "1, 2")]
    pub unix_forward_res_type: ::core::option::Option<
        unix_forward_res::UnixForwardResType,
    >,
}
/// Nested message and enum types in `unix_forward_res`.
pub mod unix_forward_res {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum UnixForwardResType {
        #[prost(message, tag = "1")]
        Remove(super::UnixForwardRemove),
        #[prost(bool, tag = "2")]
        Spindown(bool),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Request {
    #[prost(
        oneof = "request::RequestType",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21"
    )]
    pub request_type: ::core::option::Option<request::RequestType>,
}
/// Nested message and enum types in `Request`.
pub mod request {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum RequestType {
        #[prost(message, tag = "1")]
        Authenticate(super::AuthenticateRequest),
        #[prost(message, tag = "2")]
        ReadFile(super::ReadFileRequest),
        #[prost(message, tag = "3")]
        WriteFile(super::WriteFileRequest),
        #[prost(message, tag = "4")]
        DeleteFile(super::DeleteFileRequest),
        #[prost(message, tag = "5")]
        RenameFile(super::RenameFileRequest),
        #[prost(message, tag = "6")]
        ListDirectory(super::ListDirectoryRequest),
        #[prost(message, tag = "7")]
        CreateDirectory(super::CreateDirectoryRequest),
        #[prost(message, tag = "8")]
        DeleteDirectory(super::DeleteDirectoryRequest),
        #[prost(message, tag = "9")]
        GetFileInfo(super::GetFileInfoRequest),
        #[prost(message, tag = "10")]
        ListVolumes(super::ListVolumesRequest),
        #[prost(message, tag = "11")]
        GetVolumeInfo(super::GetVolumeInfoRequest),
        #[prost(message, tag = "13")]
        OpenFile(super::OpenFileRequest),
        #[prost(message, tag = "14")]
        LockFile(super::LockRequest),
        #[prost(message, tag = "15")]
        CreateFile(super::CreateFileRequest),
        #[prost(message, tag = "16")]
        CloseFile(super::CloseFileRequest),
        #[prost(message, tag = "17")]
        OverrideFile(super::OverrideFileRequest),
        #[prost(message, tag = "18")]
        Reauthenticate(super::ReAuthenticateRequest),
        #[prost(message, tag = "19")]
        Remove(super::RemoveRequest),
        #[prost(message, tag = "20")]
        FlushFile(super::FlushFileRequest),
        #[prost(message, tag = "21")]
        CanDelete(super::CanDelete),
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Response {
    #[prost(oneof = "response::ResponseType", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9")]
    pub response_type: ::core::option::Option<response::ResponseType>,
}
/// Nested message and enum types in `Response`.
pub mod response {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum ResponseType {
        #[prost(message, tag = "1")]
        AuthenticationSuccess(super::AuthenticationSuccessOuterResponse),
        #[prost(message, tag = "2")]
        FileData(super::FileDataResponse),
        #[prost(message, tag = "3")]
        WriteSuccess(super::WriteSuccessResponse),
        #[prost(message, tag = "4")]
        OperationSuccess(super::OperationSuccessResponse),
        #[prost(message, tag = "5")]
        DirectoryListing(super::DirectoryListingResponse),
        #[prost(message, tag = "6")]
        FileInfo(super::FileInfoResponse),
        #[prost(message, tag = "7")]
        VolumeList(super::VolumeListResponse),
        #[prost(message, tag = "8")]
        VolumeInfo(super::VolumeInfoResponse),
        #[prost(message, tag = "9")]
        Error(super::ErrorResponse),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthenticateRequest {
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub connection_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RemoveRequest {
    #[prost(string, tag = "1")]
    pub connection_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReAuthenticateRequest {
    #[prost(string, tag = "1")]
    pub connection_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CloseFileRequest {
    #[prost(uint64, tag = "1")]
    pub file_handler: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthenticationSuccessOuterResponse {
    #[prost(message, optional, tag = "1")]
    pub authentication_success: ::core::option::Option<AuthenticationSuccessResponse>,
    #[prost(bytes = "vec", tag = "2")]
    pub key: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AuthenticationSuccessResponse {
    #[prost(string, tag = "1")]
    pub host_name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OverrideFileRequest {
    #[prost(uint64, tag = "1")]
    pub file_id: u64,
    #[prost(bool, optional, tag = "8")]
    pub include_file_info: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReadFileRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
    #[prost(uint32, tag = "3")]
    pub length: u32,
    #[prost(uint64, tag = "4")]
    pub file_id: u64,
    #[prost(bool, tag = "5")]
    pub compress: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateFileRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub file_id: u64,
    #[prost(uint32, tag = "5")]
    pub flags: u32,
    #[prost(bool, optional, tag = "8")]
    pub include_file_info: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileDataResponse {
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
    #[prost(bool, tag = "7")]
    pub compressed: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OpenFileRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub file_id: u64,
    #[prost(uint32, tag = "4")]
    pub flags: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WriteFileRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
    #[prost(bytes = "vec", tag = "3")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    #[prost(uint64, tag = "5")]
    pub file_id: u64,
    #[prost(uint32, tag = "6")]
    pub flags: u32,
    #[prost(bool, tag = "7")]
    pub compressed: bool,
    #[prost(bool, optional, tag = "8")]
    pub include_file_info: ::core::option::Option<bool>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FlushFileRequest {
    #[prost(uint64, tag = "5")]
    pub file_id: u64,
    #[prost(bool, optional, tag = "8")]
    pub include_file_info: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CanDelete {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LockRequest {
    #[prost(uint64, tag = "1")]
    pub offset: u64,
    #[prost(uint64, tag = "2")]
    pub length: u64,
    #[prost(uint64, tag = "3")]
    pub file_id: u64,
    #[prost(bool, tag = "4")]
    pub wait: bool,
    #[prost(bool, tag = "5")]
    pub test: bool,
    #[prost(uint32, tag = "6")]
    pub flags: u32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WriteSuccessResponse {
    #[prost(uint64, tag = "1")]
    pub bytes_written: u64,
    #[prost(message, optional, tag = "2")]
    pub file_info: ::core::option::Option<FileInfoResponse>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteFileRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RenameFileRequest {
    #[prost(string, tag = "1")]
    pub old_path: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub new_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetFileInfoRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileInfoResponse {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub size: u64,
    #[prost(bool, tag = "4")]
    pub is_directory: bool,
    #[prost(int64, tag = "5")]
    pub created_at: i64,
    #[prost(int64, tag = "6")]
    pub modified_at: i64,
    #[prost(int64, tag = "7")]
    pub accessed_at: i64,
    #[prost(uint32, tag = "8")]
    pub flags: u32,
    #[prost(bool, tag = "9")]
    pub is_compressed: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListDirectoryRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DirectoryListingResponse {
    #[prost(message, repeated, tag = "1")]
    pub entries: ::prost::alloc::vec::Vec<DirectoryEntry>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DirectoryEntry {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub is_directory: bool,
    #[prost(uint64, tag = "3")]
    pub size: u64,
    #[prost(int64, tag = "4")]
    pub modified: i64,
    #[prost(int64, tag = "5")]
    pub created: i64,
    #[prost(int64, tag = "6")]
    pub accessed: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateDirectoryRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
    #[prost(bool, optional, tag = "8")]
    pub include_file_info: ::core::option::Option<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteDirectoryRequest {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
/// No fields needed
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListVolumesRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VolumeListResponse {
    #[prost(message, repeated, tag = "1")]
    pub volumes: ::prost::alloc::vec::Vec<VolumeInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetVolumeInfoRequest {
    #[prost(string, tag = "1")]
    pub volume_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VolumeInfoResponse {
    #[prost(message, optional, tag = "1")]
    pub volume: ::core::option::Option<VolumeInfo>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VolumeInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub root_path: ::prost::alloc::string::String,
    #[prost(uint64, tag = "4")]
    pub total_size: u64,
    #[prost(uint64, tag = "5")]
    pub available_space: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OperationSuccessResponse {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub file_info: ::core::option::Option<FileInfoResponse>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ErrorResponse {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
    #[prost(enumeration = "ErrorCode", tag = "2")]
    pub code: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ErrorCode {
    InternalError = 0,
    PermissionDenied = 1,
    NotFound = 2,
    AlreadyExists = 3,
    InvalidRequest = 4,
    AuthenticationFailed = 5,
    QuotaExceeded = 6,
    IoError = 7,
    InvalidInput = 8,
    IsADirectory = 9,
    NotADirectory = 10,
    InvalidFilename = 11,
}
impl ErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::InternalError => "INTERNAL_ERROR",
            Self::PermissionDenied => "PERMISSION_DENIED",
            Self::NotFound => "NOT_FOUND",
            Self::AlreadyExists => "ALREADY_EXISTS",
            Self::InvalidRequest => "INVALID_REQUEST",
            Self::AuthenticationFailed => "AUTHENTICATION_FAILED",
            Self::QuotaExceeded => "QUOTA_EXCEEDED",
            Self::IoError => "IO_ERROR",
            Self::InvalidInput => "Invalid_Input",
            Self::IsADirectory => "Is_A_Directory",
            Self::NotADirectory => "Not_A_Directory",
            Self::InvalidFilename => "Invalid_Filename",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INTERNAL_ERROR" => Some(Self::InternalError),
            "PERMISSION_DENIED" => Some(Self::PermissionDenied),
            "NOT_FOUND" => Some(Self::NotFound),
            "ALREADY_EXISTS" => Some(Self::AlreadyExists),
            "INVALID_REQUEST" => Some(Self::InvalidRequest),
            "AUTHENTICATION_FAILED" => Some(Self::AuthenticationFailed),
            "QUOTA_EXCEEDED" => Some(Self::QuotaExceeded),
            "IO_ERROR" => Some(Self::IoError),
            "Invalid_Input" => Some(Self::InvalidInput),
            "Is_A_Directory" => Some(Self::IsADirectory),
            "Not_A_Directory" => Some(Self::NotADirectory),
            "Invalid_Filename" => Some(Self::InvalidFilename),
            _ => None,
        }
    }
}
